# Generated by Django 5.2.7 on 2025-10-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='projects.project')),
            ],
            options={
                'db_table': 'project_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['portfolio', '-viewed_at'], name='portfolio_v_portfol_ab5d2b_idx'), models.Index(fields=['ip_address'], name='portfolio_v_ip_addr_6e0a2a_idx')],
            },
        ),
    ]
